# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import meet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=200)),
                ('session_id', models.CharField(default='none', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(default='none', max_length=200)),
                ('room_id', models.CharField(default='none', max_length=200)),
                ('voice_id', models.CharField(default=meet.models.get_voice_id, max_length=200)),
                ('voice_used', models.BooleanField(default=False)),
                ('state', models.IntegerField(choices=[(0, 'Staged'), (1, 'In Progress'), (2, 'Completed')], default=0)),
                ('length', models.IntegerField(default=0)),
                ('topic_time_limit', models.IntegerField(default=0)),
                ('queue_next_topic', models.BooleanField(default=False)),
                ('complete_id', models.CharField(default='none', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=200)),
                ('message_id', models.CharField(default='none', max_length=200)),
                ('time_left', models.IntegerField(default=0)),
                ('recording', models.BooleanField(default=False)),
                ('transcription', models.TextField(blank=True, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meet.Meeting')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='current_topic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='meet.Topic'),
        ),
        migrations.AddField(
            model_name='caller',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meet.Meeting'),
        ),
    ]
