# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='spark_audio',
            field=models.BooleanField(default=False),
        ),
    ]
